print ('                             |-------------| ')
print ('                             |Média escolar| ')
print ('                             |-------------| ')
print ('')
nome = input ('Entre com o nome do aluno: ')
print ('')
n1 = float (input ('Entre com a primeiro nota: '))
print ('')
n2 = float (input ('Entre com a segundo  nota: '))
print ('')
n3 = float (input ('Entre com a terceiro nota: '))
print ('')
n4 = float (input ('Entre com a quarta   nota: '))
print ('Calculando Média Escolar')
ma = (n1 + n2 + n3 + n4)/4
print ('')
print ('Nome do Aluno(a) : ',nome)
print ('Média do Aluno(a): ',ma)
print ('')
print ('                             |---------------| ')
print ('                             |Fim do processo| ')
print ('                             |---------------| ')
